project_id = "fpgxdtwmhsgikklsybql"

[functions.seed-admin]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.paypal-subscription]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.calculate]
verify_jwt = false

[functions.ga4-report]
verify_jwt = false

[functions.gsc-report]
verify_jwt = false

[functions.generate-receipt]
verify_jwt = false

[functions.seo-admin-login]
verify_jwt = false
